######################################################################
# Automatically generated by qmake (3.1) Fri Jul 8 13:50:28 2022
######################################################################

TEMPLATE = app
TARGET = mousepad
INCLUDEPATH += .

# Input
SOURCES += codeeditor.cpp main.cpp ./highlighter/*.cpp
HEADERS += codeeditor.h ./highlighter/*.h
QT += widgets